### ISSUE TITLE
Please share requirements

### ISSUE THREAD

**Issue by aleXiehta** [gtegner/mine-pytorch#2]
Hi, MI estimation is really fascinating topic, and I'm glad that there's finally an implementation of all experiments in MINE.

However, I need the system requirements to run your codes. Would you mind to share the requirements with me? (Mainly about pytorch lightning

Thanks a lot!

**Comment by jjanicechen** [comment]
Hi @aleXiehta , try pytorch-lightning 0.6.0 ?

**Comment by aleXiehta** [comment]
> Hi @aleXiehta , try pytorch-lightning 0.6.0 ?

All works well! Thank you for your help!
